---
title: "Plot Large Worlds Simulation Statistics"
author: "Jeffrey Chen"
date: "Summer 2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = F}
library(dplyr)
library(dbplyr)
source("http://www.reuningscherer.net/s&ds230/Rfuncs/regJDRS.txt")

# Create plots of iteration num vs transaction num in order to see what parameter is appropriate for numnber of iterations in a period
# No plot is shown for securities that have no transactions
# Parameters:
# period_num: int       the period of the simulation to display plot for
# max_iteration: int    maximum data point on the y-axis ie. the largest iteration number
plotIterationNums <- function(period_num, y_limit){
  transactions <- data.frame(tbl(db, sql("SELECT * FROM transactions")))
  transactions <- transactions[transactions$"period_num" == period_num,]
  for (state_num in c(0: max(transactions$state_num))) {
    cur <- transactions[transactions$"state_num" == state_num,]
    if (nrow(cur) == 0){
      next
    }
    plot(cur$transaction_num, cur$iteration_num, xlab = "Transaction Num", ylab = "Iteration Num", main = paste("Security", state_num), pch = 19, col = "blue", ylim = c(0,y_limit))
  }
}

ROUND_VALUE = 3
LABEL_OFFSET = .05
# We multiply the standard deviation to make it more readable
STDEV_MULTIPLIER = 1000

# Plot the mean price of each security as they change period by period
# No plot is shown for securities that have no transactions
plotPricesByPeriod <- function(){
  prices_by_period <- data.frame(tbl(db, sql("SELECT * FROM prices_by_period")))
  prices_by_period$st_dev <- round(prices_by_period$st_dev * STDEV_MULTIPLIER)

  num_states <- max(prices_by_period$state_num)
  num_periods <- max(prices_by_period$period_num)
  for (state_num in c(0: num_states)) {
    cur <- prices_by_period[prices_by_period$state_num == state_num,]
    if (nrow(cur) == 0){
      next
    }
    plot(cur$period_num, cur$mean, xlab = "Period number", ylab = "Mean price", main = paste("Security", state_num, "mean price by period"), col = "red", pch = 19, ylim = 0:1, type="o")
    for (i in 3:6){
      text(x = c(0: num_periods), y = cur$mean + LABEL_OFFSET * (7 - i), labels = round(cur[,i], ROUND_VALUE))
    }
  }
}

# For each security, plot the the price of the last transaction in the period versus period numbers
plotLastPricesByPeriod <- function(){
  transactions <- data.frame(tbl(db, sql("SELECT * FROM transactions")))
  max_state <- max(transactions$state_num)
  max_period <- max(transactions$period_num)
  for (security_num in c(0: max_state)) {
    cur <- transactions[transactions$state_num == security_num,]
    if (nrow(cur) == 0){
      next
    }
    # Build an array with the last transaction price in each period
    last_prices <- rep(NA, max_period + 1)
    # Iterate through each period and find the last transaction that occurred and append it to our array
    for (period_num in c(0: max_period)){
      cur_period <- cur[cur$period_num == period_num, ]
      last_transaction <- cur_period[cur_period$transaction_num == max(cur_period$transaction_num),]
      if (nrow(last_transaction) == 0){
        lastprices[period_num + 1] <- 0
      }
      else{
        last_prices[period_num + 1] <- last_transaction$price[1]
      }
    }
    plot(seq(0, max_period), last_prices, xlab = "Period Number", ylab = "Last Transaction Price", main = paste("Security", security_num, "Last Price By Period"), col = "forestgreen", pch = 19, ylim = 0:1, type = "o")
    # Label our plot with the price as well as whether or not the security was realized in that period
    text(x = c(0:max_period), y = last_prices + LABEL_OFFSET * 2, labels = round(last_prices, ROUND_VALUE))
    text(x = c(0:max_period), y = last_prices + LABEL_OFFSET, labels = data.frame(tbl(db, sql(paste("SELECT realized FROM realizations WHERE state_num =", security_num))))$realized)
  }
}

# Plot the mean price of each security from transaction to transaction across all periods
# No plot is shown for securities that have no transactions
# max_transactions: int     the number of transactions we want to see from each security provided they exist
plotPricesByTransaction <- function(max_transactions, labels = T){
  prices_by_transaction <- data.frame(tbl(db, sql("SELECT * FROM prices_by_transaction")))
  prices_by_transaction$st_dev <- round(prices_by_transaction$st_dev * STDEV_MULTIPLIER)
  num_states <- max(prices_by_transaction$state_num)
  
  for (state_num in c(0: num_states)) {
    cur <- head(prices_by_transaction[prices_by_transaction$state_num == state_num,], max_transactions)
    if (nrow(cur) == 0){
      next
    }
    num_transactions = min(max_transactions - 1, nrow(cur))
    plot(cur$transaction_num, cur$mean, xlab = "Tranasction number", ylab = "Mean price", main = paste("Security", state_num, "mean price by transaction"), col = "green", pch = 19, ylim = c(0,1), type="o")
    if (labels){
      for (i in 3:5){
        text(x = c(0: num_transactions), y = cur$mean + LABEL_OFFSET * (6 - i), labels = round(cur[,i], ROUND_VALUE))
      }
    }
  } 
}

# Plot price vs transaction number in a given period for a given security
# transactions: dataframe     all the transactions that occured, imported from SQL database
# period_num: int             period we want to plot price progression for
# state_num: int              security we want to plot price progression for
plotSecurityPeriodPriceProgression <- function (transactions, period_num, state_num, labels){
  transactions <- transactions[transactions$period_num == period_num & transactions$state_num == state_num, ]
  if (nrow(transactions) == 0){
    return()
  }
  plot(transactions$transaction_num, transactions$price, pch = 19, col = "purple", type = "o", ylim = c(0,1), xlab = "Transaction Number", ylab = "Price", main = paste("Period", period_num, "Security", state_num, "price by transaction"))
  if (labels){
   text(transactions$transaction_num, transactions$price + LABEL_OFFSET, labels = round(transactions$price, ROUND_VALUE)) 
  }
}

# Displays a set of price by transaction number plots in a given period
# Optional flag parameter enables specification of what specific states to view
#     "realized" displays only the plots of the realized securities
#     "unrealized" displays only the plots of the unrealized securities
plotPeriodPriceProgression <- function (period_num, flag = "", labels = T){
  transactions <- data.frame(tbl(db, sql("SELECT * FROM transactions")))
  
  if (flag == ""){
    num_states <- max(transactions$state_num)
    states <- c(0: num_states)
  } else if (flag %in% c("realized", "unrealized")) {
    realizations <- data.frame(tbl(db, sql("SELECT * FROM realizations")))
    realizations <- realizations[realizations$period_num == period_num, ]
    if (flag == "realized"){
      realizations <- realizations[realizations$realized == 1, ]
    }
    else {
      realizations <- realizations[realizations$realized == 0, ]
    }
    states <- realizations$state_num
  }
  else {
    print("Invalid flag input")
    return()
  }
  
  for (state_num in states) {
    plotSecurityPeriodPriceProgression(transactions, period_num, state_num, labels)
  }
}
```


```{r}
# Playground for inputs
# Enter the name of the database file you want to analyze
DB_NAME = "market5v4.db"
# Period number you to investigate further
PERIOD_NUM = 0
# Number of iterations in each period in simulation
ITERATIONS_NUM = 1 * 10 ** 6
```


```{r fig.width = 10}
db <- DBI::dbConnect(RSQLite::SQLite(), DB_NAME)
```


```{r fig.width = 10}
plotIterationNums(PERIOD_NUM, ITERATIONS_NUM)
```


```{r fig.width = 15, fig.height = 7.5}
plotPricesByPeriod()
```


```{r fig.width = 15, fig.height = 7.5}
plotLastPricesByPeriod()
```


```{r fig.width = 15, fig.height = 7.5}
#plotPricesByTransaction(20)
```

```{r fig.width = 20, fig.height = 10}
plotPeriodPriceProgression(PERIOD_NUM, "realized", F)
```

```{r fig.width = 20, fig.height = 10}
plotPeriodPriceProgression(PERIOD_NUM, "unrealized", F)
```

```{r echo = F}
# Plots 2 box plots
# First is a box plot of mean transaction price in a period based on whether security was realized vs unrealized
# Second is a boxplot of the delta mean transaction price from the previous period based on whether the current period is realized vs unrealized
# Then conducts various statistical analysis of realized vs unrealized values
securityRealizedComparison <- function(prices_by_period, security_num){
  pp <- prices_by_period[prices_by_period$state_num == security_num,]
  # Make no plots if there are no transactions
  if (nrow(pp) == 0){
    return()
  }
  
  # Mean transaction price
  unrealized_mean <- mean(pp[pp$is_realized == "Yes",]$mean)
  realized_mean <- mean(pp[pp$is_realized == "No",]$mean)
  boxplot(pp$mean ~ pp$is_realized, xlab = "Is realized?", ylab = "Mean Transaction Price in a Period", main = paste("Security", security_num, "Mean Transaction Price, Not Realized vs Realized"), col = "lightpink")
  points(c(1:2), c(unrealized_mean, realized_mean), col = "red", pch = 19)
  text(x = c(1:2), y = c(unrealized_mean, realized_mean) + .025, labels = round(c(unrealized_mean, realized_mean), 3))
  
  # We conduct statistical tests to see if there is a statistically significant difference between realized and unrealized states
  # We start with the mean transaction prices
  
  # T-Test
  print(t.test(pp$mean ~ pp$is_realized))
  
  # One way analysis of variance
  # We aim to have a factor below 2 between the maximum standard deviation and minimum standard deviation
  sds <- tapply(pp$mean, pp$is_realized, sd)
  print(paste("Factor difference between standard deviation between realized vs unrealized",max(sds) / min(sds)))
  securityAOV <- aov(pp$mean ~ pp$is_realized)
  print(summary(securityAOV))
  myResPlots2(securityAOV)
  
  # Delta mean transaction price
  max_period <- max(pp$period_num)
  pp$delta <- NA
  for (num_period in c(1:max_period)){
    pp[num_period,]$delta <- pp$mean[num_period + 1] - pp$mean[num_period]
  }
  # We have to exclude the first period because there is no previous period to compare to
  pp <- pp[!is.na(pp$delta),]
  unrealized_delta_mean <- mean(pp[pp$is_realized == "No",]$delta)
  realized_delta_mean <- mean(pp[pp$is_realized == "Yes",]$delta)
  boxplot(pp$delta ~ pp$is_realized, xlab = "Is realized?", ylab = "Delta Mean Transaction Price in a Period", main = paste("Security", security_num, "Delta Mean Transaction Price, Not Realized vs Realized"), col = "lightyellow")
  points(c(1:2), c(unrealized_delta_mean, realized_delta_mean), col = "red", pch = 19)
  text(x = c(1:2), y = c(unrealized_delta_mean, realized_delta_mean) + .025, labels = round(c(unrealized_delta_mean, realized_delta_mean), 3))
  

  print(t.test(pp$delta ~ pp$is_realized))
  
  sds <- tapply(pp$delta, pp$is_realized, sd)
  print(paste("Factor difference between standard deviation between realized vs unrealized",max(sds) / min(sds)))
  securityAOV <- aov(pp$delta ~ pp$is_realized)
  print(summary(securityAOV))
  myResPlots2(securityAOV)
}

# Plots security realized comparison of mean transaction prices for all securities
realizedComparison <- function(){
  pp <- data.frame(tbl(db, sql("SELECT * FROM prices_by_period")))
  pp$is_realized <- NA
  pp[pp$realized == "1",]$is_realized <- "Yes"
  pp[pp$realized == "0",]$is_realized <- "No"
  
  max_state <- max(pp$state_num)
  for (num_state in c(0:max_state)){
    securityRealizedComparison(pp, num_state)
  }
  
  # One way analysis of variance
  hist(pp[pp$is_realized == "Yes",]$mean, main = "Overall Mean Transaction Price, Realized", col = "lightgreen", xlab = "Mean Transaction Price in a Period", breaks = 50)
  hist(pp[pp$is_realized == "No",]$mean, main = "Overall Mean Transaction Price, Unrealized", col = "lightsalmon", xlab = "Mean Transaction Price in a Period", breaks = 50)
  # We aim to have a factor below 2 between the maximum standard deviation and minimum standard deviation
  sds <- tapply(pp$mean, pp$is_realized, sd)
  print(max(sds) / min(sds))
  securityAOV <- aov(pp$mean ~ pp$is_realized)
  print(summary(securityAOV))
  myResPlots2(securityAOV)
}
```

```{r}
#realizedComparison()
```


