---
title: "Simulation Statistics"
author: "Jeffrey Chen"
date: "Summer 2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning = F}
library(dplyr)
library(dbplyr)

# Create plots of iteration num vs transaction num in order to see what parameter is appropriate for numnber of iterations in a period
plotIterationNums <- function(period_num){
  transactions <- data.frame(tbl(db, sql("SELECT * FROM transactions")))
  transactions <- transactions[transactions$"period_num" == period_num,]
  for (state_num in c(0: max(transactions$state_num))) {
    cur <- transactions[transactions$"state_num" == state_num,]
    plot(cur$transaction_num, cur$iteration_num, xlab = "Transaction Num", ylab = "Iteration Num", main = paste("Security", state_num), pch = 19, col = "blue")
  }
}

LABEL_OFFSET = .05
STDEV_MULTIPLIER = 1000

# Plot the mean price of each security as they change period by period
plotPricesByPeriod <- function(){
  prices_by_period <- data.frame(tbl(db, sql("SELECT * FROM prices_by_period")))
  prices_by_period$st_dev <- round(prices_by_period$st_dev * STDEV_MULTIPLIER)

  num_states = max(prices_by_period$state_num)
  num_periods = max(prices_by_period$period_num)
  for (state_num in c(0: num_states)) {
    cur <- prices_by_period[prices_by_period$state_num == state_num,]
    plot(cur$period_num, cur$mean, xlab = "Period number", ylab = "Mean", main = paste("Security", state_num, "price by period"), col = "red", pch = 19, ylim = 0:1, type="o")
    for (i in 3:6){
      text(x = c(0: num_periods), y = cur$mean + LABEL_OFFSET * (7 - i), labels = round(cur[,i], 3))
    }
  }
}

# Plot the mean price of each security from transaction to transaction across all periods
# max_transactions represents the number of transactions we want to see from each security provided they exist
plotPricesByTransaction <- function(max_transactions){
  prices_by_transaction <- data.frame(tbl(db, sql("SELECT * FROM prices_by_transaction")))
  prices_by_transaction$st_dev <- round(prices_by_transaction * STDEV_MULTIPLIER)
  num_states = max(prices_by_transaction$state_num)
  
  for (state_num in c(0: num_states)) {
    cur <- head(prices_by_transaction[prices_by_transaction$state_num == state_num,], max_transactions)
    num_transactions = min(max_transactions - 1, nrow(cur))
    plot(cur$transaction_num, cur$mean, xlab = "Tranasction number", ylab = "Mean", main = paste("Security", state_num, "price by transaction"), col = "red", pch = 19, ylim = 0:1, type="o")
    for (i in 3:5){
      text(x = c(0: num_transactions), y = cur$mean + LABEL_OFFSET * (6 - i), labels = round(cur[,i], 3))
    }
  } 
}
```


```{r fig.width = 10}
db_name = "test2.db"
db <- DBI::dbConnect(RSQLite::SQLite(), db_name)
#plotIterationNums(0)
plotPricesByPeriod()
plotPricesByTransaction(20)
```